Dim swApp As Object
Dim Part As Object
Dim SelMgr As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Dim Feature As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Set SelMgr = Part.SelectionManager
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.InsertCurveFileBegin
Part.InsertCurveFilePoint 0.082500, 0.001256, 0
Part.InsertCurveFilePoint 0.082294, 0.001256, 0.005819
Part.InsertCurveFilePoint 0.081679, 0.001256, 0.011610
Part.InsertCurveFilePoint 0.080657, 0.001256, 0.017343
Part.InsertCurveFilePoint 0.079232, 0.001256, 0.022989
Part.InsertCurveFilePoint 0.077413, 0.001256, 0.028521
Part.InsertCurveFilePoint 0.075209, 0.001256, 0.033910
Part.InsertCurveFilePoint 0.072629, 0.001256, 0.039131
Part.InsertCurveFilePoint 0.069688, 0.001256, 0.044157
Part.InsertCurveFilePoint 0.066400, 0.001256, 0.048962
Part.InsertCurveFilePoint 0.062781, 0.001256, 0.053524
Part.InsertCurveFilePoint 0.058849, 0.001256, 0.057819
Part.InsertCurveFilePoint 0.054624, 0.001256, 0.061826
Part.InsertCurveFilePoint 0.050126, 0.001256, 0.065525
Part.InsertCurveFilePoint 0.045380, 0.001256, 0.068898
Part.InsertCurveFilePoint 0.040406, 0.001256, 0.071927
Part.InsertCurveFilePoint 0.035232, 0.001256, 0.074599
Part.InsertCurveFilePoint 0.029882, 0.001256, 0.076898
Part.InsertCurveFilePoint 0.024384, 0.001256, 0.078814
Part.InsertCurveFilePoint 0.018763, 0.001256, 0.080338
Part.InsertCurveFilePoint 0.013050, 0.001256, 0.081461
Part.InsertCurveFilePoint 0.007271, 0.001256, 0.082179
Part.InsertCurveFilePoint 0.001456, 0.001256, 0.082487
Part.InsertCurveFilePoint -0.004366, 0.001256, 0.082384
Part.InsertCurveFilePoint -0.010167, 0.001256, 0.081871
Part.InsertCurveFilePoint -0.015916, 0.001256, 0.080950
Part.InsertCurveFilePoint -0.021587, 0.001256, 0.079626
Part.InsertCurveFilePoint -0.027150, 0.001256, 0.077905
Part.InsertCurveFilePoint -0.032578, 0.001256, 0.075795
Part.InsertCurveFilePoint -0.037843, 0.001256, 0.073309
Part.InsertCurveFilePoint -0.042920, 0.001256, 0.070457
Part.InsertCurveFilePoint -0.047783, 0.001256, 0.067254
Part.InsertCurveFilePoint -0.052408, 0.001256, 0.063716
Part.InsertCurveFilePoint -0.056772, 0.001256, 0.059860
Part.InsertCurveFilePoint -0.060853, 0.001256, 0.055706
Part.InsertCurveFilePoint -0.064631, 0.001256, 0.051275
Part.InsertCurveFilePoint -0.068086, 0.001256, 0.046588
Part.InsertCurveFilePoint -0.071203, 0.001256, 0.041670
Part.InsertCurveFilePoint -0.073965, 0.001256, 0.036543
Part.InsertCurveFilePoint -0.076359, 0.001256, 0.031235
Part.InsertCurveFilePoint -0.078372, 0.001256, 0.025771
Part.InsertCurveFilePoint -0.079994, 0.001256, 0.020178
Part.InsertCurveFilePoint -0.081218, 0.001256, 0.014485
Part.InsertCurveFilePoint -0.082038, 0.001256, 0.008720
Part.InsertCurveFilePoint -0.082449, 0.001256, 0.002912
Part.InsertCurveFilePoint -0.082449, 0.001256, -0.002912
Part.InsertCurveFilePoint -0.082038, 0.001256, -0.008720
Part.InsertCurveFilePoint -0.081218, 0.001256, -0.014485
Part.InsertCurveFilePoint -0.079994, 0.001256, -0.020178
Part.InsertCurveFilePoint -0.078372, 0.001256, -0.025771
Part.InsertCurveFilePoint -0.076359, 0.001256, -0.031235
Part.InsertCurveFilePoint -0.073965, 0.001256, -0.036543
Part.InsertCurveFilePoint -0.071203, 0.001256, -0.041670
Part.InsertCurveFilePoint -0.068086, 0.001256, -0.046588
Part.InsertCurveFilePoint -0.064631, 0.001256, -0.051275
Part.InsertCurveFilePoint -0.060853, 0.001256, -0.055706
Part.InsertCurveFilePoint -0.056772, 0.001256, -0.059860
Part.InsertCurveFilePoint -0.052408, 0.001256, -0.063716
Part.InsertCurveFilePoint -0.047783, 0.001256, -0.067254
Part.InsertCurveFilePoint -0.042920, 0.001256, -0.070457
Part.InsertCurveFilePoint -0.037843, 0.001256, -0.073309
Part.InsertCurveFilePoint -0.032578, 0.001256, -0.075795
Part.InsertCurveFilePoint -0.027150, 0.001256, -0.077905
Part.InsertCurveFilePoint -0.021587, 0.001256, -0.079626
Part.InsertCurveFilePoint -0.015916, 0.001256, -0.080950
Part.InsertCurveFilePoint -0.010167, 0.001256, -0.081871
Part.InsertCurveFilePoint -0.004366, 0.001256, -0.082384
Part.InsertCurveFilePoint 0.001456, 0.001256, -0.082487
Part.InsertCurveFilePoint 0.007271, 0.001256, -0.082179
Part.InsertCurveFilePoint 0.013050, 0.001256, -0.081461
Part.InsertCurveFilePoint 0.018763, 0.001256, -0.080338
Part.InsertCurveFilePoint 0.024384, 0.001256, -0.078814
Part.InsertCurveFilePoint 0.029882, 0.001256, -0.076898
Part.InsertCurveFilePoint 0.035232, 0.001256, -0.074599
Part.InsertCurveFilePoint 0.040406, 0.001256, -0.071927
Part.InsertCurveFilePoint 0.045380, 0.001256, -0.068898
Part.InsertCurveFilePoint 0.050126, 0.001256, -0.065525
Part.InsertCurveFilePoint 0.054624, 0.001256, -0.061826
Part.InsertCurveFilePoint 0.058849, 0.001256, -0.057819
Part.InsertCurveFilePoint 0.062781, 0.001256, -0.053524
Part.InsertCurveFilePoint 0.066400, 0.001256, -0.048962
Part.InsertCurveFilePoint 0.069688, 0.001256, -0.044157
Part.InsertCurveFilePoint 0.072629, 0.001256, -0.039131
Part.InsertCurveFilePoint 0.075209, 0.001256, -0.033910
Part.InsertCurveFilePoint 0.077413, 0.001256, -0.028521
Part.InsertCurveFilePoint 0.079232, 0.001256, -0.022989
Part.InsertCurveFilePoint 0.080657, 0.001256, -0.017343
Part.InsertCurveFilePoint 0.081679, 0.001256, -0.011610
Part.InsertCurveFilePoint 0.082294, 0.001256, -0.005819
Part.InsertCurveFilePoint 0.082500, 0.001256, -0.000000
Part.InsertCurveFileEnd
End Sub
