Dim swApp As Object
Dim Part As Object
Dim SelMgr As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Dim Feature As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Set SelMgr = Part.SelectionManager
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.InsertCurveFileBegin
Part.InsertCurveFilePoint 0.031647, 0, 0.600000
Part.InsertCurveFilePoint 0.031622, 0.000004, 0.600000
Part.InsertCurveFilePoint 0.031533, 0.000018, 0.600000
Part.InsertCurveFilePoint 0.031498, 0.000023, 0.600000
Part.InsertCurveFilePoint 0.031067, 0.000010, 0.600000
Part.InsertCurveFilePoint 0.030989, -0.000011, 0.600000
Part.InsertCurveFilePoint 0.030228, -0.000263, 0.600000
Part.InsertCurveFilePoint 0.030118, -0.000292, 0.600000
Part.InsertCurveFilePoint 0.029055, -0.000533, 0.600000
Part.InsertCurveFilePoint 0.028921, -0.000565, 0.600000
Part.InsertCurveFilePoint 0.027574, -0.000893, 0.600000
Part.InsertCurveFilePoint 0.027422, -0.000930, 0.600000
Part.InsertCurveFilePoint 0.025790, -0.001377, 0.600000
Part.InsertCurveFilePoint 0.025625, -0.001427, 0.600000
Part.InsertCurveFilePoint 0.023714, -0.002047, 0.600000
Part.InsertCurveFilePoint 0.023544, -0.002104, 0.600000
Part.InsertCurveFilePoint 0.021362, -0.002826, 0.600000
Part.InsertCurveFilePoint 0.021195, -0.002879, 0.600000
Part.InsertCurveFilePoint 0.018747, -0.003606, 0.600000
Part.InsertCurveFilePoint 0.018584, -0.003651, 0.600000
Part.InsertCurveFilePoint 0.015885, -0.004334, 0.600000
Part.InsertCurveFilePoint 0.015725, -0.004372, 0.600000
Part.InsertCurveFilePoint 0.012795, -0.005003, 0.600000
Part.InsertCurveFilePoint 0.012638, -0.005034, 0.600000
Part.InsertCurveFilePoint 0.009497, -0.005599, 0.600000
Part.InsertCurveFilePoint 0.009344, -0.005624, 0.600000
Part.InsertCurveFilePoint 0.006017, -0.006117, 0.600000
Part.InsertCurveFilePoint 0.005866, -0.006137, 0.600000
Part.InsertCurveFilePoint 0.002371, -0.006562, 0.600000
Part.InsertCurveFilePoint 0.002224, -0.006579, 0.600000
Part.InsertCurveFilePoint -0.001416, -0.006944, 0.600000
Part.InsertCurveFilePoint -0.001561, -0.006957, 0.600000
Part.InsertCurveFilePoint -0.005321, -0.007266, 0.600000
Part.InsertCurveFilePoint -0.005462, -0.007276, 0.600000
Part.InsertCurveFilePoint -0.009323, -0.007529, 0.600000
Part.InsertCurveFilePoint -0.009462, -0.007537, 0.600000
Part.InsertCurveFilePoint -0.013402, -0.007727, 0.600000
Part.InsertCurveFilePoint -0.013537, -0.007732, 0.600000
Part.InsertCurveFilePoint -0.017533, -0.007850, 0.600000
Part.InsertCurveFilePoint -0.017664, -0.007852, 0.600000
Part.InsertCurveFilePoint -0.021702, -0.007890, 0.600000
Part.InsertCurveFilePoint -0.021830, -0.007890, 0.600000
Part.InsertCurveFilePoint -0.025878, -0.007852, 0.600000
Part.InsertCurveFilePoint -0.026003, -0.007850, 0.600000
Part.InsertCurveFilePoint -0.030061, -0.007744, 0.600000
Part.InsertCurveFilePoint -0.030183, -0.007740, 0.600000
Part.InsertCurveFilePoint -0.034249, -0.007580, 0.600000
Part.InsertCurveFilePoint -0.034368, -0.007575, 0.600000
Part.InsertCurveFilePoint -0.038412, -0.007367, 0.600000
Part.InsertCurveFilePoint -0.038526, -0.007360, 0.600000
Part.InsertCurveFilePoint -0.042520, -0.007108, 0.600000
Part.InsertCurveFilePoint -0.042630, -0.007100, 0.600000
Part.InsertCurveFilePoint -0.046542, -0.006810, 0.600000
Part.InsertCurveFilePoint -0.046647, -0.006801, 0.600000
Part.InsertCurveFilePoint -0.050444, -0.006481, 0.600000
Part.InsertCurveFilePoint -0.050544, -0.006473, 0.600000
Part.InsertCurveFilePoint -0.054193, -0.006136, 0.600000
Part.InsertCurveFilePoint -0.054288, -0.006127, 0.600000
Part.InsertCurveFilePoint -0.057755, -0.005789, 0.600000
Part.InsertCurveFilePoint -0.057847, -0.005780, 0.600000
Part.InsertCurveFilePoint -0.061099, -0.005456, 0.600000
Part.InsertCurveFilePoint -0.061187, -0.005448, 0.600000
Part.InsertCurveFilePoint -0.064192, -0.005150, 0.600000
Part.InsertCurveFilePoint -0.064278, -0.005142, 0.600000
Part.InsertCurveFilePoint -0.067002, -0.004877, 0.600000
Part.InsertCurveFilePoint -0.067086, -0.004869, 0.600000
Part.InsertCurveFilePoint -0.069501, -0.004636, 0.600000
Part.InsertCurveFilePoint -0.069585, -0.004627, 0.600000
Part.InsertCurveFilePoint -0.071665, -0.004379, 0.600000
Part.InsertCurveFilePoint -0.071747, -0.004368, 0.600000
Part.InsertCurveFilePoint -0.073476, -0.004087, 0.600000
Part.InsertCurveFilePoint -0.073556, -0.004072, 0.600000
Part.InsertCurveFilePoint -0.074947, -0.003802, 0.600000
Part.InsertCurveFilePoint -0.075022, -0.003790, 0.600000
Part.InsertCurveFilePoint -0.076087, -0.003713, 0.600000
Part.InsertCurveFilePoint -0.076146, -0.003707, 0.600000
Part.InsertCurveFilePoint -0.076846, -0.003508, 0.600000
Part.InsertCurveFilePoint -0.076881, -0.003503, 0.600000
Part.InsertCurveFilePoint -0.077120, -0.003548, 0.600000
Part.InsertCurveFilePoint -0.077142, -0.003561, 0.600000
Part.InsertCurveFilePoint -0.077208, -0.003613, 0.600000
Part.InsertCurveFileEnd
End Sub
