Dim swApp As Object
Dim Part As Object
Dim SelMgr As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Dim Feature As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Set SelMgr = Part.SelectionManager
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.InsertCurveFileBegin
Part.InsertCurveFilePoint 0.037500, 0.001256, 0
Part.InsertCurveFilePoint 0.037407, 0.001256, 0.002645
Part.InsertCurveFilePoint 0.037127, 0.001256, 0.005277
Part.InsertCurveFilePoint 0.036662, 0.001256, 0.007883
Part.InsertCurveFilePoint 0.036015, 0.001256, 0.010449
Part.InsertCurveFilePoint 0.035188, 0.001256, 0.012964
Part.InsertCurveFilePoint 0.034186, 0.001256, 0.015414
Part.InsertCurveFilePoint 0.033013, 0.001256, 0.017787
Part.InsertCurveFilePoint 0.031676, 0.001256, 0.020071
Part.InsertCurveFilePoint 0.030182, 0.001256, 0.022256
Part.InsertCurveFilePoint 0.028537, 0.001256, 0.024329
Part.InsertCurveFilePoint 0.026749, 0.001256, 0.026281
Part.InsertCurveFilePoint 0.024829, 0.001256, 0.028103
Part.InsertCurveFilePoint 0.022785, 0.001256, 0.029784
Part.InsertCurveFilePoint 0.020627, 0.001256, 0.031317
Part.InsertCurveFilePoint 0.018367, 0.001256, 0.032694
Part.InsertCurveFilePoint 0.016015, 0.001256, 0.033908
Part.InsertCurveFilePoint 0.013583, 0.001256, 0.034954
Part.InsertCurveFilePoint 0.011083, 0.001256, 0.035825
Part.InsertCurveFilePoint 0.008529, 0.001256, 0.036517
Part.InsertCurveFilePoint 0.005932, 0.001256, 0.037028
Part.InsertCurveFilePoint 0.003305, 0.001256, 0.037354
Part.InsertCurveFilePoint 0.000662, 0.001256, 0.037494
Part.InsertCurveFilePoint -0.001985, 0.001256, 0.037447
Part.InsertCurveFilePoint -0.004621, 0.001256, 0.037214
Part.InsertCurveFilePoint -0.007235, 0.001256, 0.036795
Part.InsertCurveFilePoint -0.009812, 0.001256, 0.036194
Part.InsertCurveFilePoint -0.012341, 0.001256, 0.035411
Part.InsertCurveFilePoint -0.014808, 0.001256, 0.034452
Part.InsertCurveFilePoint -0.017201, 0.001256, 0.033322
Part.InsertCurveFilePoint -0.019509, 0.001256, 0.032026
Part.InsertCurveFilePoint -0.021719, 0.001256, 0.030570
Part.InsertCurveFilePoint -0.023822, 0.001256, 0.028962
Part.InsertCurveFilePoint -0.025805, 0.001256, 0.027209
Part.InsertCurveFilePoint -0.027660, 0.001256, 0.025321
Part.InsertCurveFilePoint -0.029378, 0.001256, 0.023307
Part.InsertCurveFilePoint -0.030948, 0.001256, 0.021177
Part.InsertCurveFilePoint -0.032365, 0.001256, 0.018941
Part.InsertCurveFilePoint -0.033621, 0.001256, 0.016611
Part.InsertCurveFilePoint -0.034708, 0.001256, 0.014198
Part.InsertCurveFilePoint -0.035623, 0.001256, 0.011714
Part.InsertCurveFilePoint -0.036361, 0.001256, 0.009172
Part.InsertCurveFilePoint -0.036917, 0.001256, 0.006584
Part.InsertCurveFilePoint -0.037290, 0.001256, 0.003964
Part.InsertCurveFilePoint -0.037477, 0.001256, 0.001323
Part.InsertCurveFilePoint -0.037477, 0.001256, -0.001323
Part.InsertCurveFilePoint -0.037290, 0.001256, -0.003964
Part.InsertCurveFilePoint -0.036917, 0.001256, -0.006584
Part.InsertCurveFilePoint -0.036361, 0.001256, -0.009172
Part.InsertCurveFilePoint -0.035623, 0.001256, -0.011714
Part.InsertCurveFilePoint -0.034708, 0.001256, -0.014198
Part.InsertCurveFilePoint -0.033621, 0.001256, -0.016611
Part.InsertCurveFilePoint -0.032365, 0.001256, -0.018941
Part.InsertCurveFilePoint -0.030948, 0.001256, -0.021177
Part.InsertCurveFilePoint -0.029378, 0.001256, -0.023307
Part.InsertCurveFilePoint -0.027660, 0.001256, -0.025321
Part.InsertCurveFilePoint -0.025805, 0.001256, -0.027209
Part.InsertCurveFilePoint -0.023822, 0.001256, -0.028962
Part.InsertCurveFilePoint -0.021719, 0.001256, -0.030570
Part.InsertCurveFilePoint -0.019509, 0.001256, -0.032026
Part.InsertCurveFilePoint -0.017201, 0.001256, -0.033322
Part.InsertCurveFilePoint -0.014808, 0.001256, -0.034452
Part.InsertCurveFilePoint -0.012341, 0.001256, -0.035411
Part.InsertCurveFilePoint -0.009812, 0.001256, -0.036194
Part.InsertCurveFilePoint -0.007235, 0.001256, -0.036795
Part.InsertCurveFilePoint -0.004621, 0.001256, -0.037214
Part.InsertCurveFilePoint -0.001985, 0.001256, -0.037447
Part.InsertCurveFilePoint 0.000662, 0.001256, -0.037494
Part.InsertCurveFilePoint 0.003305, 0.001256, -0.037354
Part.InsertCurveFilePoint 0.005932, 0.001256, -0.037028
Part.InsertCurveFilePoint 0.008529, 0.001256, -0.036517
Part.InsertCurveFilePoint 0.011083, 0.001256, -0.035825
Part.InsertCurveFilePoint 0.013583, 0.001256, -0.034954
Part.InsertCurveFilePoint 0.016015, 0.001256, -0.033908
Part.InsertCurveFilePoint 0.018367, 0.001256, -0.032694
Part.InsertCurveFilePoint 0.020627, 0.001256, -0.031317
Part.InsertCurveFilePoint 0.022785, 0.001256, -0.029784
Part.InsertCurveFilePoint 0.024829, 0.001256, -0.028103
Part.InsertCurveFilePoint 0.026749, 0.001256, -0.026281
Part.InsertCurveFilePoint 0.028537, 0.001256, -0.024329
Part.InsertCurveFilePoint 0.030182, 0.001256, -0.022256
Part.InsertCurveFilePoint 0.031676, 0.001256, -0.020071
Part.InsertCurveFilePoint 0.033013, 0.001256, -0.017787
Part.InsertCurveFilePoint 0.034186, 0.001256, -0.015414
Part.InsertCurveFilePoint 0.035188, 0.001256, -0.012964
Part.InsertCurveFilePoint 0.036015, 0.001256, -0.010449
Part.InsertCurveFilePoint 0.036662, 0.001256, -0.007883
Part.InsertCurveFilePoint 0.037127, 0.001256, -0.005277
Part.InsertCurveFilePoint 0.037407, 0.001256, -0.002645
Part.InsertCurveFilePoint 0.037500, 0.001256, -0.000000
Part.InsertCurveFileEnd
End Sub
