Dim swApp As Object
Dim Part As Object
Dim SelMgr As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Dim Feature As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Set SelMgr = Part.SelectionManager
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.InsertCurveFileBegin
Part.InsertCurveFilePoint -0.129161, -0.121885, 0.120060
Part.InsertCurveFilePoint -0.118008, -0.109617, 0.134132
Part.InsertCurveFilePoint -0.108172, -0.099225, 0.148204
Part.InsertCurveFilePoint -0.099456, -0.090235, 0.162276
Part.InsertCurveFilePoint -0.091665, -0.082301, 0.176348
Part.InsertCurveFilePoint -0.084736, -0.075242, 0.190420
Part.InsertCurveFilePoint -0.078605, -0.068913, 0.204491
Part.InsertCurveFilePoint -0.073218, -0.063200, 0.218563
Part.InsertCurveFilePoint -0.068525, -0.058013, 0.232635
Part.InsertCurveFilePoint -0.064482, -0.053276, 0.246707
Part.InsertCurveFilePoint -0.061049, -0.048928, 0.260779
Part.InsertCurveFilePoint -0.058185, -0.044918, 0.274851
Part.InsertCurveFilePoint -0.055875, -0.041207, 0.288922
Part.InsertCurveFilePoint -0.054161, -0.037776, 0.302994
Part.InsertCurveFilePoint -0.052977, -0.034575, 0.317066
Part.InsertCurveFilePoint -0.052252, -0.031566, 0.331138
Part.InsertCurveFilePoint -0.051973, -0.028730, 0.345210
Part.InsertCurveFilePoint -0.052202, -0.026453, 0.359282
Part.InsertCurveFilePoint -0.052934, -0.023896, 0.373353
Part.InsertCurveFilePoint -0.054014, -0.021441, 0.387425
Part.InsertCurveFilePoint -0.055525, -0.019078, 0.401497
Part.InsertCurveFilePoint -0.057527, -0.016782, 0.415569
Part.InsertCurveFilePoint -0.059843, -0.014539, 0.429641
Part.InsertCurveFilePoint -0.062543, -0.012329, 0.443713
Part.InsertCurveFilePoint -0.065685, -0.010124, 0.457784
Part.InsertCurveFilePoint -0.069108, -0.007924, 0.471856
Part.InsertCurveFilePoint -0.072868, -0.005706, 0.485928
Part.InsertCurveFilePoint -0.077208, -0.003387, 0.500000
Part.InsertCurveFileEnd
End Sub
