Dim swApp As Object
Dim Part As Object
Dim SelMgr As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Dim Feature As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Set SelMgr = Part.SelectionManager
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.InsertCurveFileBegin
Part.InsertCurveFilePoint 37.500000, 133.857545, 0.000000
Part.InsertCurveFilePoint 37.381456, 133.857545, 2.979381
Part.InsertCurveFilePoint 37.026575, 133.857545, 5.939926
Part.InsertCurveFilePoint 36.437600, 133.857545, 8.862916
Part.InsertCurveFilePoint 35.618255, 133.857545, 11.729873
Part.InsertCurveFilePoint 34.573720, 133.857545, 14.522669
Part.InsertCurveFilePoint 33.310598, 133.857545, 17.223648
Part.InsertCurveFilePoint 31.836876, 133.857545, 19.815734
Part.InsertCurveFilePoint 30.161871, 133.857545, 22.282539
Part.InsertCurveFilePoint 28.296173, 133.857545, 24.608466
Part.InsertCurveFilePoint 26.251578, 133.857545, 26.778810
Part.InsertCurveFilePoint 24.041011, 133.857545, 28.779850
Part.InsertCurveFilePoint 21.678450, 133.857545, 30.598935
Part.InsertCurveFilePoint 19.178830, 133.857545, 32.224563
Part.InsertCurveFilePoint 16.557956, 133.857545, 33.646457
Part.InsertCurveFilePoint 13.832397, 133.857545, 34.855628
Part.InsertCurveFilePoint 11.019385, 133.857545, 35.844430
Part.InsertCurveFilePoint 8.136705, 133.857545, 36.606612
Part.InsertCurveFilePoint 5.202582, 133.857545, 37.137355
Part.InsertCurveFilePoint 2.235567, 133.857545, 37.433304
Part.InsertCurveFilePoint -0.745582, 133.857545, 37.492587
Part.InsertCurveFilePoint -3.722017, 133.857545, 37.314831
Part.InsertCurveFilePoint -6.674921, 133.857545, 36.901158
Part.InsertCurveFilePoint -9.585624, 133.857545, 36.254183
Part.InsertCurveFilePoint -12.435723, 133.857545, 35.377999
Part.InsertCurveFilePoint -15.207200, 133.857545, 34.278143
Part.InsertCurveFilePoint -17.882531, 133.857545, 32.961570
Part.InsertCurveFilePoint -20.444804, 133.857545, 31.436603
Part.InsertCurveFilePoint -22.877818, 133.857545, 29.712883
Part.InsertCurveFilePoint -25.166191, 133.857545, 27.801310
Part.InsertCurveFilePoint -27.295455, 133.857545, 25.713967
Part.InsertCurveFilePoint -29.252149, 133.857545, 23.464053
Part.InsertCurveFilePoint -31.023901, 133.857545, 21.065791
Part.InsertCurveFilePoint -32.599510, 133.857545, 18.534345
Part.InsertCurveFilePoint -33.969015, 133.857545, 15.885718
Part.InsertCurveFilePoint -35.123756, 133.857545, 13.136657
Part.InsertCurveFilePoint -36.056434, 133.857545, 10.304541
Part.InsertCurveFilePoint -36.761151, 133.857545, 7.407277
Part.InsertCurveFilePoint -37.233453, 133.857545, 4.463182
Part.InsertCurveFilePoint -37.470352, 133.857545, 1.490869
Part.InsertCurveFilePoint -37.470352, 133.857545, -1.490869
Part.InsertCurveFilePoint -37.233453, 133.857545, -4.463182
Part.InsertCurveFilePoint -36.761151, 133.857545, -7.407277
Part.InsertCurveFilePoint -36.056434, 133.857545, -10.304541
Part.InsertCurveFilePoint -35.123756, 133.857545, -13.136657
Part.InsertCurveFilePoint -33.969015, 133.857545, -15.885718
Part.InsertCurveFilePoint -32.599510, 133.857545, -18.534345
Part.InsertCurveFilePoint -31.023901, 133.857545, -21.065791
Part.InsertCurveFilePoint -29.252149, 133.857545, -23.464053
Part.InsertCurveFilePoint -27.295455, 133.857545, -25.713967
Part.InsertCurveFilePoint -25.166191, 133.857545, -27.801310
Part.InsertCurveFilePoint -22.877818, 133.857545, -29.712883
Part.InsertCurveFilePoint -20.444804, 133.857545, -31.436603
Part.InsertCurveFilePoint -17.882531, 133.857545, -32.961570
Part.InsertCurveFilePoint -15.207200, 133.857545, -34.278143
Part.InsertCurveFilePoint -12.435723, 133.857545, -35.377999
Part.InsertCurveFilePoint -9.585624, 133.857545, -36.254183
Part.InsertCurveFilePoint -6.674921, 133.857545, -36.901158
Part.InsertCurveFilePoint -3.722017, 133.857545, -37.314831
Part.InsertCurveFilePoint -0.745582, 133.857545, -37.492587
Part.InsertCurveFilePoint 2.235567, 133.857545, -37.433304
Part.InsertCurveFilePoint 5.202582, 133.857545, -37.137355
Part.InsertCurveFilePoint 8.136705, 133.857545, -36.606612
Part.InsertCurveFilePoint 11.019385, 133.857545, -35.844430
Part.InsertCurveFilePoint 13.832397, 133.857545, -34.855628
Part.InsertCurveFilePoint 16.557956, 133.857545, -33.646457
Part.InsertCurveFilePoint 19.178830, 133.857545, -32.224563
Part.InsertCurveFilePoint 21.678450, 133.857545, -30.598935
Part.InsertCurveFilePoint 24.041011, 133.857545, -28.779850
Part.InsertCurveFilePoint 26.251578, 133.857545, -26.778810
Part.InsertCurveFilePoint 28.296173, 133.857545, -24.608466
Part.InsertCurveFilePoint 30.161871, 133.857545, -22.282539
Part.InsertCurveFilePoint 31.836876, 133.857545, -19.815734
Part.InsertCurveFilePoint 33.310598, 133.857545, -17.223648
Part.InsertCurveFilePoint 34.573720, 133.857545, -14.522669
Part.InsertCurveFilePoint 35.618255, 133.857545, -11.729873
Part.InsertCurveFilePoint 36.437600, 133.857545, -8.862916
Part.InsertCurveFilePoint 37.026575, 133.857545, -5.939926
Part.InsertCurveFilePoint 37.381456, 133.857545, -2.979381
Part.InsertCurveFilePoint 37.500000, 133.857545, -0.000000
Part.InsertCurveFileEnd
End Sub
