Dim swApp As Object
Dim Part As Object
Dim SelMgr As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Dim Feature As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.ActiveDoc
Set SelMgr = Part.SelectionManager
swApp.ActiveDoc.ActiveView.FrameState = 1
Part.InsertCurveFileBegin
Part.InsertCurveFilePoint 52.500000, -1.350431, 0.000000
Part.InsertCurveFilePoint 52.334039, -1.350431, 4.171134
Part.InsertCurveFilePoint 51.837205, -1.350431, 8.315896
Part.InsertCurveFilePoint 51.012640, -1.350431, 12.408083
Part.InsertCurveFilePoint 49.865557, -1.350431, 16.421822
Part.InsertCurveFilePoint 48.403207, -1.350431, 20.331737
Part.InsertCurveFilePoint 46.634837, -1.350431, 24.113108
Part.InsertCurveFilePoint 44.571627, -1.350431, 27.742028
Part.InsertCurveFilePoint 42.226620, -1.350431, 31.195554
Part.InsertCurveFilePoint 39.614643, -1.350431, 34.451852
Part.InsertCurveFilePoint 36.752209, -1.350431, 37.490334
Part.InsertCurveFilePoint 33.657416, -1.350431, 40.291790
Part.InsertCurveFilePoint 30.349830, -1.350431, 42.838509
Part.InsertCurveFilePoint 26.850363, -1.350431, 45.114388
Part.InsertCurveFilePoint 23.181139, -1.350431, 47.105040
Part.InsertCurveFilePoint 19.365356, -1.350431, 48.797879
Part.InsertCurveFilePoint 15.427139, -1.350431, 50.182202
Part.InsertCurveFilePoint 11.391387, -1.350431, 51.249257
Part.InsertCurveFilePoint 7.283615, -1.350431, 51.992297
Part.InsertCurveFilePoint 3.129794, -1.350431, 52.406625
Part.InsertCurveFilePoint -1.043815, -1.350431, 52.489622
Part.InsertCurveFilePoint -5.210824, -1.350431, 52.240763
Part.InsertCurveFilePoint -9.344890, -1.350431, 51.661621
Part.InsertCurveFilePoint -13.419873, -1.350431, 50.755857
Part.InsertCurveFilePoint -17.410012, -1.350431, 49.529198
Part.InsertCurveFilePoint -21.290079, -1.350431, 47.989400
Part.InsertCurveFilePoint -25.035544, -1.350431, 46.146198
Part.InsertCurveFilePoint -28.622726, -1.350431, 44.011244
Part.InsertCurveFilePoint -32.028945, -1.350431, 41.598037
Part.InsertCurveFilePoint -35.232667, -1.350431, 38.921834
Part.InsertCurveFilePoint -38.213638, -1.350431, 35.999554
Part.InsertCurveFilePoint -40.953009, -1.350431, 32.849674
Part.InsertCurveFilePoint -43.433462, -1.350431, 29.492107
Part.InsertCurveFilePoint -45.639314, -1.350431, 25.948082
Part.InsertCurveFilePoint -47.556621, -1.350431, 22.240005
Part.InsertCurveFilePoint -49.173259, -1.350431, 18.391319
Part.InsertCurveFilePoint -50.479007, -1.350431, 14.426358
Part.InsertCurveFilePoint -51.465612, -1.350431, 10.370188
Part.InsertCurveFilePoint -52.126834, -1.350431, 6.248455
Part.InsertCurveFilePoint -52.458493, -1.350431, 2.087217
Part.InsertCurveFilePoint -52.458493, -1.350431, -2.087217
Part.InsertCurveFilePoint -52.126834, -1.350431, -6.248455
Part.InsertCurveFilePoint -51.465612, -1.350431, -10.370188
Part.InsertCurveFilePoint -50.479007, -1.350431, -14.426358
Part.InsertCurveFilePoint -49.173259, -1.350431, -18.391319
Part.InsertCurveFilePoint -47.556621, -1.350431, -22.240005
Part.InsertCurveFilePoint -45.639314, -1.350431, -25.948082
Part.InsertCurveFilePoint -43.433462, -1.350431, -29.492107
Part.InsertCurveFilePoint -40.953009, -1.350431, -32.849674
Part.InsertCurveFilePoint -38.213638, -1.350431, -35.999554
Part.InsertCurveFilePoint -35.232667, -1.350431, -38.921834
Part.InsertCurveFilePoint -32.028945, -1.350431, -41.598037
Part.InsertCurveFilePoint -28.622726, -1.350431, -44.011244
Part.InsertCurveFilePoint -25.035544, -1.350431, -46.146198
Part.InsertCurveFilePoint -21.290079, -1.350431, -47.989400
Part.InsertCurveFilePoint -17.410012, -1.350431, -49.529198
Part.InsertCurveFilePoint -13.419873, -1.350431, -50.755857
Part.InsertCurveFilePoint -9.344890, -1.350431, -51.661621
Part.InsertCurveFilePoint -5.210824, -1.350431, -52.240763
Part.InsertCurveFilePoint -1.043815, -1.350431, -52.489622
Part.InsertCurveFilePoint 3.129794, -1.350431, -52.406625
Part.InsertCurveFilePoint 7.283615, -1.350431, -51.992297
Part.InsertCurveFilePoint 11.391387, -1.350431, -51.249257
Part.InsertCurveFilePoint 15.427139, -1.350431, -50.182202
Part.InsertCurveFilePoint 19.365356, -1.350431, -48.797879
Part.InsertCurveFilePoint 23.181139, -1.350431, -47.105040
Part.InsertCurveFilePoint 26.850363, -1.350431, -45.114388
Part.InsertCurveFilePoint 30.349830, -1.350431, -42.838509
Part.InsertCurveFilePoint 33.657416, -1.350431, -40.291790
Part.InsertCurveFilePoint 36.752209, -1.350431, -37.490334
Part.InsertCurveFilePoint 39.614643, -1.350431, -34.451852
Part.InsertCurveFilePoint 42.226620, -1.350431, -31.195554
Part.InsertCurveFilePoint 44.571627, -1.350431, -27.742028
Part.InsertCurveFilePoint 46.634837, -1.350431, -24.113108
Part.InsertCurveFilePoint 48.403207, -1.350431, -20.331737
Part.InsertCurveFilePoint 49.865557, -1.350431, -16.421822
Part.InsertCurveFilePoint 51.012640, -1.350431, -12.408083
Part.InsertCurveFilePoint 51.837205, -1.350431, -8.315896
Part.InsertCurveFilePoint 52.334039, -1.350431, -4.171134
Part.InsertCurveFilePoint 52.500000, -1.350431, -0.000000
Part.InsertCurveFileEnd
End Sub
